### ISSUE TITLE
Question: Does this spawn a daemon?

### ISSUE THREAD

**Issue by Gene-Dana** [tobimd/ipfs_http_rpc#1]
Hi there ! I've spent some time recently researching this topic and I'm unsure whether or not this package spawns a daemon. Does it?

**Comment by tobimd** [comment]
Hello! The answer is no, it only uses the calls over HTTP and, when creating the `ipfs` object, you can specify if using localhost or any other url where the daemon/server would be receiving the calls.

**Comment by Gene-Dana** [comment]
Any guidance you can share on how you can spawn a daemon?

**Comment by tobimd** [comment]
The daemon is an app or script which will try to fetch data sent to it via commands or HTTP RPC like what this package does.

[Ipfs install](https://ipfs.tech/#install) provides a desktop app, a command-line utility and other stuff. You can install the binaries directly or even the go/js implementations.

You can see more at [ipfs basics](https://docs.ipfs.tech/basics/)

**Comment by Gene-Dana** [comment]
I meant any guidance you can share about spawning IPFS from a mobile device

**Comment by tobimd** [comment]
A member of a team I'm working with, used the Go implementation of Ipfs and compiled it specifically for the mobile architecture we are using. This was done for testing and demo reasons obviously, but the other more realistic option is to have a server running the client and just connecting to it from the mobile device. 

It's not necessary to have the binary run inside the mobile device (not to mention the security problems that could happen).

**Comment by Gene-Dana** [comment]
At the end of the day, the distributed web becomes distributed when everyone using it participates. Being that 90% of all internet interactions happen on the phone, to me it seems like surmounting the mobile obstacle is the only option.

I may be wrong, and I'm really just learning. Thank you for the share !
