### ISSUE TITLE
Demo Web App in Documention

### ISSUE THREAD

**Issue by draftin1** [tobimd/ipfs_http_rpc#2]
I'd find it helpful if there were documentation on how to use this package with a web app.

**Comment by tobimd** [comment]
Hi, generally speaking, the way this package works does not depend on architecture/device. Maybe it would be good to specify that the way that these type of packages work (as far as I know, at least this one does), is by connecting to the external running IPFS daemon using it's HTTP API. This means that it doesn't spawn an instance, but only expects the HTTP endpoint.

Would something like that help (adding an explanation about this package only connecting to the daemon) or did you mean something else?
